# @package _global_

# Be careful when using _raw, history
obs:
  obs_dict:
    actor_obs: [
      base_ang_vel,
      projected_gravity,
      command_lin_vel,
      command_ang_vel,
      dof_pos,
      dof_vel,
      actions,
      short_history
    ]

    critic_obs: [
      base_lin_vel,
      base_ang_vel,
      projected_gravity,
      command_lin_vel,
      command_ang_vel,
      dof_pos,
      dof_vel,
      actions,
      dr_base_com,
      dr_link_mass,
      dr_kp,
      dr_kd,
      dr_friction,
      dr_ctrl_delay,
      short_history
    ]

  # define those coumpounds in obs_dict, for example, you can define different long/short history with different length
  obs_auxiliary: 
    short_history: {
      base_ang_vel: 5,
      projected_gravity: 5,
      dof_pos: 5,
      dof_vel: 5,
      actions: 5,
      command_lin_vel: 5,
      command_ang_vel: 5,
    }

  obs_scales: {
    base_lin_vel: 2.0,
    base_ang_vel: 0.25,
    projected_gravity: 1.0,
    command_lin_vel: 1.0,
    command_ang_vel: 1.0,
    dof_pos: 1.0,
    dof_vel: 0.05,
    history: 1.0,
    short_history: 1.0,
    actions: 1.0,
    dr_base_com: 1.0,
    dr_link_mass: 1.0,
    dr_kp: 1.0,
    dr_kd: 1.0,
    dr_friction: 1.0,
    dr_ctrl_delay: 1.0,
  }

  noise_scales: {
    base_lin_vel: 0.0,
    base_ang_vel: 0.0,
    projected_gravity: 0.0,
    command_lin_vel: 0.0,
    command_ang_vel: 0.0,
    dof_pos: 0.0,
    dof_vel: 0.0,
    actions: 0.0,
    history: 0.0,
    short_history: 0.0,
    dr_base_com: 0.0,
    dr_link_mass: 0.0,
    dr_kp: 0.0,
    dr_kd: 0.0,
    dr_friction: 0.0,
    dr_ctrl_delay: 0.0,

  }

  add_noise_currculum: False
  noise_initial_value: 0.05
  noise_value_max: 1.00
  noise_value_min: 0.00001
  soft_dof_pos_curriculum_degree: 0.00001
  soft_dof_pos_curriculum_level_down_threshold: 100
  soft_dof_pos_curriculum_level_up_threshold: 900

  # obs_dims should use list instead of dict
  # will be converted to dict in `pre_process_config`
  obs_dims:
    - base_lin_vel: 3
    - base_ang_vel: 3
    - projected_gravity: 3
    - command_lin_vel: 2
    - command_ang_vel: 1
    - dof_pos: ${robot.dof_obs_size}
    - dof_vel: ${robot.dof_obs_size}
    - actions: ${robot.dof_obs_size}
    - dr_base_com: 3
    - dr_link_mass: 9 # = num of 'randomize_link_body_names'
    - dr_kp: ${robot.dof_obs_size}
    - dr_kd: ${robot.dof_obs_size}
    - dr_friction: 1
    - dr_ctrl_delay: 1
  motion_len: -1